name: Prereleased

on:
  release:
    types:
    - prereleased

jobs:
  cancel_previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    needs:
    - cancel_previous
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
    - name: Version
      id: version
      run: echo ::set-output name=value::${GITHUB_REF#refs/*/}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
    - prepare
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - uses: Swatinem/rust-cache@v1
